# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IneiKyiGzhNVrW40o-HwEOkvqKwnDH78
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib
import random


lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()


unique_values = data["whoAmI"].unique()
one_hot_data = pd.DataFrame()

for value in unique_values:
    one_hot_data[value] = (data["whoAmI"] == value).astype(int)

one_hot_data.head()